### ISSUE TITLE
Update: http://docs.plone.org/adapt-and-extend/config/dexterity-content-types.html

### ISSUE THREAD

**Issue by svx** [plone/documentation#677] opened 2016-07-27 08:06 UTC
So we have Plone 5 now since quite some time released, great !!!

One of the many awesome features is besides a screen-shot **not** documented at all ...

For people who work with content a lot, this is a important feature !

Given that you are able to use d.c.t for as a replacement for various add-ons you need in Plone 4, we should update this part of the docs asap, we also should add some nice and easy examples :)

**Comment by tkimnguyen** [comment] 2016-07-28 14:12
Which feature are you referring to?

**Comment by polyester** [comment] 2016-07-28 14:21
there is no proper documentation for changing dexterity types TTW.
 (both as in 'formal documentation of all settings and buttons' and as in 'descriptive blog-style human account on why this is the best thing since sliced bread') 

iirc, there were some screencast/gifs made by @esteele for various keynotes; might be worth exploring if we can integrate those.

**Comment by stevepiercy** [comment] 2024-10-02 09:01
Closing as duplicate of any of these issues: https://github.com/plone/documentation/issues?q=is%3Aissue+is%3Aopen+dexterity

**Closed as completed by stevepiercy** 2024-10-02 09:01 UTC
Labels: 04 type: enhancement, 99 tag: Plone 5.x
