### ISSUE TITLE
robot screenshots Plone 5 fail, because no option to add content.

### ISSUE THREAD

**Issue by polyester** [plone/documentation#239] opened 2015-05-03 12:03 UTC
Trying to get some robotscreenshots for Plone 5, for now just testing out with the https://github.com/plone/documentation/blob/5.0/working-with-content/adding-content/adding-events.rst first test. 

By adding "Pause" to the robot-test I can see that I'm logged in as "Jane Doe", but the robottestsite is completely empty, and also does not have any option to add content. Thus, I cannot even begin changing the css selectors.

@datakurre is there some extra stuff that needs to go in _robots.rst to set up a working testsite for 5.0?

To replicate:
- mkdir doc5
- cd doc5
- git clone https://github.com/plone/papyrus.git
- virtualenv --no-site-packages papyrus
- cd papyrus
- ./bin/python bootstrap-buildout.py
- git checkout 5.0
- bin/buildout
- make externals
- add "Pause" to source/documentation/working-with-content/adding-content/adding-events.rst, just after        Go to  ${PLONE_URL} (with a blank line separating. You will want python-tk to be installed for this)
- make html

- examine the now open firefox. It's Plone5, but not as we know it...

**Comment by datakurre** [comment] 2015-05-03 12:14
@polyester Thanks for poking. Probably only thing really missing (besides abstracting different selectors for Plone 4 and Plone 5) is installing plone.app.contenttypes when on Plone 5. I'm not sure, why that's not installed with the default "Plone test sandbox" similarly to Archetypes and ATContenttypes were in Plone 4.

Mind a few days.

**Comment by datakurre** [comment] 2015-05-03 12:16
So, technically, I should add Plone 5 support for plone.app.robotframework.

**Comment by datakurre** [comment] 2015-05-03 12:18
@polyester Oh, I forgot that p.a.contettypes probably can be installed also in _robot.rst

**Comment by polyester** [comment] 2015-05-03 12:19
ah, that would solve it. I'll see if I understand _robots.rst

**Comment by datakurre** [comment] 2015-05-03 12:20
Maybe

    *** Variables ***

    @{APPLY_PROFILES}  plone.app.contenttypes:default  plone.app.iterate:plone.app.iterate

**Comment by datakurre** [comment] 2015-05-03 12:22
plone.app.iterate-part is required only in working-copy.rst

@{APPLY_PROFILES}  is a double space separated list of installed profiles on top of the default Plone sandbox fixture.

**Comment by datakurre** [comment] 2015-05-03 12:23
Technically it's a feature of a special test fixture provided by plone.app.robotframework as in

    *** Variables ***

    ${FIXTURE}  plone.app.robotframework.PLONE_ROBOT_TESTING

**Comment by polyester** [comment] 2015-05-03 12:31
the @{APPLY_PROFILES} seems to do the trick... thanks! Enough to start playing, at least.

**Comment by datakurre** [comment] 2015-05-03 12:37
+1

**Comment by polyester** [comment] 2015-05-03 12:52
reopening for now; there's a bunch of weird error messages like

[ WARN ] plone.dexterity.schema.generated.plone_0_News_1_Item is not an instance of SchemaClass. This can happen if the first base class of a schema is not a SchemaClass. See https://bugs.launchpad.net/zope.interface/+bug/791218

and plone.app.iterate won't be installed. There may be a few other profiles missing.  But definitely on the right track. I'll keep hunting a bit more.

**Comment by datakurre** [comment] 2015-05-03 13:13
I've seen those warnings, but they are more Plone than robot related.

About profiles,

    @{APPLY_PROFILES}  plone.app.contenttypes:default  plone.app.iterate:plone.app.iterate

should take any amount of profiles as "double space" separated list (which should be possible to also split to multiple lines with the following syntax

    @{APPLY_PROFILES}  plone.app.contenttypes:default
    ...                plone.app.iterate:plone.app.iterate

Yet, if some document file defines ``@{APPLY_PROFILES}`` again, it should always include all profiles (it's not cumulative).

In that regard, there should be no differences between Plone 4 and Plone 5. So, if plone.app.iterate really is missing, it's definitely interesting.

**Comment by polyester** [comment] 2015-07-14 20:32
OK, first success, I can now make robot-screenshots for Plone 5. Will document the changes. plone.app.iterate does not work for now, but that has deeper reasons, nothing to do with robotframework for now.

but note to future self: it would be good to have a 'plone-kitchensink' fixture which has everything we ship with already enabled.

**Comment by datakurre** [comment] 2015-07-14 23:00
That's great news.  I'm sorry that I've not been able to help enough :/

polyester kirjoitti ti heinäkuuta 14 23:32:23 2015 GMT+0300:

**Comment by datakurre** [comment] 2015-07-14 23:23
> but note to future self: it would be good to have a 'plone-kitchensink' fixture which has everything we ship with already enabled.

Given the list of "everything", I'd expect it to be already possible with the robot configurable fixture used in docs.

Also, now that you have been struggling enough with robot, could it be made easier somehow? Any ideas? (Of course, we always have options to script screenshots in Python [no need for robot syntax, but probably still not easie] or just take them manually as before [and they outdate].)

plone.app.iterate issue sounds like scripted screenshots can also point regression sometimes?

**Comment by polyester** [comment] 2015-07-15 09:16
well, the actual screenshot-making is easy enough, and pretty clearly documented.

I struggled a lot with finding clear docs (and maybe an easier way) of installing a product/add-on, enabling it if needed, enable a behaviour  on contenttypes, or set other options in the site management screen, all before actually starting the 'real' test/screenshot to show how to use that add-on.

And yes, scripted screenshots are useful, because they do point out underlying issues as well.

**Comment by datakurre** [comment] 2015-07-15 09:45
> I struggled a lot with finding clear docs (and maybe an easier way) of installing a product/add-on, enabling it if needed, enable a behaviour  on contenttypes, or set other options in the site management screen, all before actually starting the 'real' test/screenshot to show how to use that add-on.


These are good points. Add-ons can be activated, but it's not documented outside examples. Other configuration has no helpers. I should add support / keyword for importing tarballed GenericSetup export (it could be the one shop for almost any configuration) and write a chapter about all these into robot docs.

**Comment by djay** [comment] 2015-07-15 10:29
So cool. 7 years in the making
- 2008 - http://sourceforge.net/p/plone/mailman/message/21138247/
- 2009 - http://sourceforge.net/p/plone/mailman/message/21992350/
until asko finally made it happen.

**Comment by svx** [comment] 2015-07-29 10:00
We are almost there, but I found a new issue:

the screen-shots are not consistent between Firefox and phantom.js :(

If I use Firefox as browser for Robot Framework, configured in my Sphinx conf.py

sphinxcontrib_robotframework_variables = {
    "BROWSER": "Firefox"  # 'Firefox' is the default
}

 everything is working
![adding_news_item_firefox](https://cloud.githubusercontent.com/assets/358860/8954890/dce2572a-35e8-11e5-8495-21fa5b839fdc.png)

If I tell sphinx to use phantomjs:

sphinxcontrib_robotframework_variables = {
    "BROWSER": "phantomjs"  # 'Firefox' is the default
}

I do not get the pictures of the toolbar:

![adding_news_items_phantomjs](https://cloud.githubusercontent.com/assets/358860/8954911/0a90b234-35e9-11e5-88ce-221a892f24bd.png)

and I got the following message:

![adding_news_items_phantom_ci](https://cloud.githubusercontent.com/assets/358860/8954921/1c276470-35e9-11e5-9c77-7d1dbcf54ea4.png)
 
I am testing that, because I try to run papyrus in docker and rkt, so far the first test a really positive ! Only thing what we do have to fix are this issue for now :)

**Comment by datakurre** [comment] 2015-07-29 10:30
That could be an unfortunate issue with PhantomJS webdriver/Selenium 
integration :(

So, it should be Xvfb + Firefox then? Running multiple processes in a 
Docker container is never fun, but I'm sure you can figure out a nice 
way to wrap them.

Xvfb should run like

/usr/bin/Xvfb -fp /usr/share/fonts/X11/misc/ :99 -screen 0 1280x1024x24

where :99 is the DISPLAY.

sven wrote:

**Comment by svx** [comment] 2015-07-29 10:34
Not sure yet, if Xvfb + Firefox would be the right solution, but I will try that soon :)

**Comment by svx** [comment] 2015-07-29 11:38
a second test with phantomjs 2.0 cloned from github and compiled gives the same results for me, maybe someone else want to test that ?

For the first test I was using phantomjs 1.9 via ap-get [trusty]

As for docker, we could try to link to containers together, one with papyrus and one with Firefox and Xvfb ?

**Comment by polyester** [comment] 2015-07-29 16:30
yeah, phantomjs 1.9.8 (via npm) gives same result.

**Comment by svx** [comment] 2016-08-25 12:07
@polyester can we close this ?

**Closed** 2016-08-25 12:33 UTC
Labels: 99 tag: Plone 5
