### ISSUE TITLE
functionality/controlpanel.html: prefix used in ZCML without corresponding schema_prefix leading to unhelpful traceback

### ISSUE THREAD

**Issue by flipmcf** [plone/documentation#1021] opened 2018-10-04 21:17 UTC
* **I'm submitting a ...**
  - [X ] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Documentation - https://docs.plone.org/develop/plone/functionality/controlpanel.html

Is confusing with the usage of a Plone registry schema prefix

First, one encounters: `<records interface="silvuple.settings.ISettings" prefix="silvuple">`
Without the 'prefix' being explained.

Then you encounter `TagSettingsEditForm(controlpanel.RegistryEditForm):`
which does not define `schema_prefix`

And you find yourself at:
KeyError: 'Interface
`MyProduct.controlpanel.ISchema` defines a field 
`foo`, for which there is no record.'

And you have no clue what you did wrong.  (until you visit @pbauer 's mastering plone, of course )

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
Either describe schema_prefix or remove prefix from .zcml 

* **What is the motivation / use case for changing the behavior?**
I wasted 3 hours debugging the KeyError and ended up spelunking into plone.registry.registry.forInterface and plone.app.registry.browser.controlpanel.RegistryEditForm` to find `schema_prefix = None`  - googled `schema_prefix` and found better docs under mastering plone.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Try to build a control panel using only the docs from https://docs.plone.org/develop/plone/functionality/controlpanel.html

Normally, I'd just open a PR, but this one might need some discussion.

**Comment by stevepiercy** [comment] 2024-11-23 14:26
Closing as can't reproduce and won't fix. Please reopen if this issue persists Plone 6.

**Closed as completed by stevepiercy** 2024-11-23 14:26 UTC
