### ISSUE TITLE
Version button for 5.1 splits on characters not list items

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#926] opened 2017-10-22 09:12 UTC
Thanks to #920, I built the docs locally and found a UI bug. The version button for the v5.1 docs splits on characters instead of list items. See screenshot.
![Version button](https://user-images.githubusercontent.com/102112/31860410-ea01b1da-b719-11e7-9b24-a648b9c9b8eb.png)

**Comment by polyester** [comment] 2017-10-26 14:59
If someone can take a peek, in https://github.com/plone/sphinxtheme.plone/commit/5da4991f0bf0a6f4ef8436a94db6569451f2feeb the problem is explained a bit more. I'm following syntax as also used by Alabaster, but somehow it fails. 

Note it works perfectly fine when setting the options in a sphinx conf.py format, just not in a (INI-style) theme.conf format.

Anybody with more experience in python and/or sphinx? @stevepiercy @loechel

**Comment by stevepiercy** [comment] 2017-10-26 20:17
I found [this comment](https://github.com/bitprophet/alabaster/commit/4bf18059524f24f1d9f2424e6927e597da81564a), which in turn reminded me that [INI supports only strings](https://docs.python.org/3/library/configparser.html#supported-datatypes).

So the correct configuration value in `theme.conf` would be a single '345', but that won't work for '5.1'.

Is there a problem with using the `html_theme_options` setting in `conf.py`?

```python
html_theme_options = {
    #...
    'version_drop' : [
        'master',
        '5',
        '4',
        '3',
    ],
    #...    
}
```

**Comment by polyester** [comment] 2017-10-26 20:27
Nope, in conf.py everything works just peachy, and with exactly the syntax you said. It's just in the theme.conf (in INI style) that it doesn't work. We could just leave it at that:

- putting it at "543" in theme.conf within sphinxtheme.plone will give us reasonable defaults in a tox file, when working on sphinxtheme.plone just to test new development on the theme
- for the "real deal", we can use proper conf.py syntax, and everything will work.

it's not ideal for the obsessive-compulsive amongst  us, but it works for me ;-)

**Comment by svx** [comment] 2017-10-31 07:48
ping @polyester do you know the status of this ? 

I would like to push a new version of the docs asap ! :)

Thanks !

**Comment by polyester** [comment] 2017-10-31 08:29
this is as good as it will get for now, as INI syntax only supports strings. As long as papyrus has a proper definition in conf.py, it works. We could push a new version of sphinxthemes.plone so this oddity is at least documented.

**Comment by svx** [comment] 2017-10-31 08:36
I am sorry I am confused, when I tried to build the docs last week I hit exactly this issue.

Do I assume right that is solved in papyrus with: https://github.com/plone/papyrus/commit/e56e683cc19eb2ca67955490e42eec7b0cc8bb7d ?

Do we need another release of the theme ? 

Do we need a release for 'documenting' ? I guess it depends how and where you want to do that, right ?
For adding docs in /docs or add a note in the README we do not need a new release. right ?

**Comment by polyester** [comment] 2017-10-31 08:39
yeah, in papyrus it's solved with that pull.

We don't need a new release of the theme, with https://github.com/plone/sphinxtheme.plone/commit/5da4991f0bf0a6f4ef8436a94db6569451f2feeb it just makes it so that it looks nicer when using tox or when not setting things correctly in conf.py, but it is a bit much to do a sphinxtheme.plone release just for that. Wait with that until there is something substantial to release.

**Comment by svx** [comment] 2017-10-31 08:41
Ok thanks ! Will prepare and hopefully push a new docs version at the end of the week/weekend then.

Thanks !

**Comment by svx** [comment] 2017-11-06 14:37
Docs are pushed, I will close this issue for now. Thanks all !

**Closed as completed by svx** 2017-11-06 14:37 UTC
