### ISSUE TITLE
Update: buildout docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#278] opened 2015-06-18 18:42 UTC
Currently we have under _http://docs.plone.org/old-reference-manuals/buildout/_ some docs about buildout, these docs are outdated.
- we should update them
- we should add missing stuff 
- we should find a new place _old-reference-manuals_ will be not included in the docs for Plone 5

**Comment by jensens** [comment] 2015-07-14 10:48
the problem is, that the original zc.buildout documentation was and is complete crap, so we did our own. You can not point people to http://www.buildout.org/en/latest/ and also the doctest style pseudo documentation at https://pypi.python.org/pypi/zc.buildout/2.4.0 is even for hardcore pythonistas difficult to read.

so we should update this old home-grown manual.

**Comment by svx** [comment] 2017-02-02 13:21
It is gone in the 5 docs, but still in the [4 docs](http://docs.plone.org/4/en/old-reference-manuals/buildout/index.html?highlight=buildout) is that still needed in 5/5.x ?

**Comment by stevepiercy** [comment] 2024-11-06 08:57
We have started to migrate the "homegrown version" of buildout docs at https://4.docs.plone.org/old-reference-manuals/buildout/ as mentioned by @jensens into Plone 6 documentation on an "as needed" basis. PR #1746 was part of this effort. There is now a reference to the homegrown version in the Glossary, instead of the poorly structured and written versions from `zc.buildout` and Buildout.

@petschki @yurj @MrTango @davisagli @mauritsvanrees @gforcada pinging y'all to be aware of this resource, as we continue documenting the use of Buildout in Plone 6 Documentation. Thanks to @polyester for keeping it running!

Closing as completed in #1746 and #1757.

**Closed by stevepiercy** 2024-11-06 08:57 UTC
Labels: 04 type: enhancement
