### ISSUE TITLE
Screenshot of TinyMCE broken

### ISSUE THREAD

**Issue by pbauer** [plone/documentation#976] opened 2018-03-19 07:40 UTC
The screenshot at https://5.docs.plone.org/working-with-content/using-tinymce-as-visual-editor/basics.html (https://docs.plone.org/_images/tinymce.png) is broken.

**Comment by sonawanemaitreya** [comment] 2018-03-25 10:56
use this image instead - 
[https://lh3.googleusercontent.com/-dqvvSHvwduE/Wrd__Rrsx0I/AAAAAAAABPY/4yxDQpaGwAQmd2ogbnpt_PN9wjWKaC3egCJoC/w530-h330-n-rw/default%2BTiny%2BMCE.png](url)

**Comment by sonawanemaitreya** [comment] 2018-03-25 10:58
Use this image instead:-
[https://lh3.googleusercontent.com/-dqvvSHvwduE/Wrd__Rrsx0I/AAAAAAAABPY/4yxDQpaGwAQmd2ogbnpt_PN9wjWKaC3egCJoC/w530-h330-n-rw/default%2BTiny%2BMCE.png](url)

**Comment by sonawanemaitreya** [comment] 2018-03-25 11:00
[https://plus.google.com/photos/photo/105916059823020349018/6536834109206742850?sqid=108887112685013305463&ssid=e809e1b9-ed79-46e8-b27d-f72812e1cac6](url)

**Comment by sonawanemaitreya** [comment] 2018-03-25 11:04
Use image in here-
[https://sites.google.com/site/defaulttinymce/home](url)

**Comment by sonawanemaitreya** [comment] 2018-03-25 11:09
![default tiny mce](https://user-images.githubusercontent.com/33842949/37874357-1c1af78a-304b-11e8-9f8f-b01f8a01ef53.png)
You can use this image instead

**Comment by stevepiercy** [comment] 2022-08-25 21:22
This issue is still broken. Reopening. The PR #984 that was intended to fix this was self-merged then reverted because the image is automatically generated.

I added a milestone of 5.2 as the last version that it would affect.

**Comment by stevepiercy** [comment] 2024-11-23 14:30
Closing as won't fix.

**Closed as completed by stevepiercy** 2024-11-23 14:30 UTC
