### ISSUE TITLE
https://github.com/collective/bobtemplates.plone

### ISSUE THREAD

**Issue by svx** [plone/documentation#193] opened 2015-02-06 15:19 UTC
should we add this to the docs ?

if so to which version ?

**Comment by gforcada** [comment] 2015-02-06 15:55
Big :+1: as for which version, @tisto has been doing some work lately targeted at Plone 5 so I would say that we most probably only want to start talking about it on Plone 5 and keep the zopeskel/templer mess on plone 4

**Comment by svx** [comment] 2015-02-06 16:02
@gforcada sounds good I will add this to the list for Plone 5 docs.
@tisto, @pbauer  do you know if there is a plan to move from collective to the core repo ?.
If they move to core I can auto-include, otherwise I will have to link

**Comment by plone-foundation** [comment] 2015-02-07 17:48
This is more urgent than we may have thought. There is some nasty
compatibility problem between the Zopeskel localcommand framework and
current setuptools.

**Comment by polyester** [comment] 2015-02-07 18:43
How far back is mr.bob and bobtemplates compatible? Does it work on 4.0-4.2? If so, I say we change quickly. If not, we have an issue...

**Comment by pbauer** [comment] 2015-02-07 18:47
I would gladly move bobtemplates.plone to the plone-repo. Do I need to get the permission for all the other commiters? Regarding versions I think it should be in Plone 4 and 5 since it supports both. I never tried using an addon created with bobtemplates.plone in anything older than Plone 4.3 but will do so and I don't think there is anything in it that prevents the addons to work. Although the buildout that comes with the addons is for now allways using Plone 4.3.4.

**Comment by polyester** [comment] 2015-02-07 18:59
@pbauer , only on Cedric (https://github.com/cedricmessiant) I'm not sure he has already signed a Contributor Agreement (he should anyway ;-)

so he'd be the one to ask.

**Comment by pbauer** [comment] 2015-02-07 19:05
I asked him

**Comment by pbauer** [comment] 2015-02-07 19:19
And I just tried a addon with Plone 4.2.7, 4.1.6 and saw no problems. I could not get it to run in 4.0.10 and was too lazy to spand time on that since I think that is acceptable.

**Comment by polyester** [comment] 2015-02-07 19:28
OK, assuming Cedric can be contacted so we can pull the whole bobtemplates doc into documentation proper,  that would mean (just listing it here, not saying I'll write it within the next few days.....)
- deprecating https://github.com/plone/documentation/blob/master/develop/addons/paste.rst as "the" solution, yet still keeping it around for reference (at least for 4.x branch)
- adding bobtemplates here as the new best practice, both for 4.x and 5.x
- changing first paragraphs of https://github.com/plone/documentation/blob/master/develop/addons/dexterity.rst as well.

All doable, just needs some love.

**Comment by svx** [comment] 2015-02-08 07:24
just let me know when I can change and I will do it

**Comment by pbauer** [comment] 2015-02-09 10:07
@cedricmessiant confirmed that he already signed over his soul to Plone. I created https://github.com/plone/bobtemplates.plone and will move https://github.com/collective/bobtemplates.plone there

**Comment by svx** [comment] 2015-02-09 10:13
OK I see the new repo in core :) I will work on this during the next days to make sure it will be in the next docs release which will be in around two weeks

**Comment by polyester** [comment] 2015-02-09 10:17
Then some of the admins should also add @cedricmessiant to the Plone org repo.

**Comment by svx** [comment] 2015-02-09 10:34
He is already a member

**Comment by polyester** [comment] 2015-02-09 10:38
hmm, I see only 'collective' in his profile. But OK, this is getting offtopic

**Comment by svx** [comment] 2015-02-09 11:02
me too but if I check the member of the organization it shows me that he is a member

**Comment by plone-foundation** [comment] 2015-02-09 21:21
Thanks, Philip. I think you've done adequate diligence. If someone needs
template code for 4.0.x, they can just grab the 4.0.x unified installer.

**Comment by svx** [comment] 2015-02-16 08:51
New branch: https://github.com/plone/documentation/tree/bobtemplates_p4

@polyester: I did not changed https://github.com/plone/documentation/blob/master/develop/addons/dexterity.rst, since we can't do that with bobtemplates, yet

**Comment by svx** [comment] 2015-04-27 19:07
Removing paster parts form the docs is currently way more work, the whole section /develop is full of it.
So I am all in for removing/update it for Plone 5 but what shall we do with Plone 4 docs ?

**Comment by svx** [comment] 2015-04-30 17:04
just to be sure I will ask one last time, is it OK with everyone that I start to remove *all* paster/zopeskel parts from the 5 branch ?

**Comment by cewing** [comment] 2015-04-30 18:29
:pray: :clap: :fireworks:

**Comment by gforcada** [comment] 2015-04-30 22:53
Yes please! :)

**Comment by svx** [comment] 2015-05-04 14:07
Ok I will refactor and update the branch like:

we are pulling bobtemplates to /develop and reference to it.

For all existing paster docs in the 4 branch, we will add that paster is depreciated and also will link/refence to bobtemplates.

For Plone 5 docs, we will rip paster out :)

Cool with everyone ?

**Comment by svx** [comment] 2015-05-14 15:05
PR is out ! The only thing what is missing now, is updating the docs of diazo and dexterity, this has to be done in their repos since we just fetch them.
I can do that but, I prefer if someone with more knowledge of diazo, dexterity and bobtemplates.plone could do that, to make sure the docs are correct and everything works.

If someone wants to do that, but want help for the docs part of it, ping me!

To give a bit motivation, this is the last bit what is missing before we can push a huge, I mean it, a **HUGE** update to docs.plone.org, including pre-alpha Plone 5 docs and nightly builds of all our docs to preview.docs.plone.org.

**Comment by svx** [comment] 2015-08-10 13:53
any takers for diazo and dexterity ?

**Comment by polyester** [comment] 2015-08-10 13:59
Unfortunately (well), Mikel Larreategi (@erral) created a nice diazo5-barceloneta based codeskel just  a week or so ago, see https://github.com/codesyntax/CodeSkel

Maybe that can be more or less easily re-used as a bobtemplates one?

**Comment by svx** [comment] 2015-08-10 14:10
I know but I was more referring to:  *The only thing what is missing now, is updating the docs of diazo and dexterity, this has to be done in their repos since we just fetch them*

So the docs/readmes in the github repos of diazo and dexterity are needing updates, because there are still talking about paster, this should be changed to mr.bob templates if that is possible of course, otherwise we still have paster in the docs.

:)

**Comment by polyester** [comment] 2015-08-10 14:12
yup, I was trying to avoid having a new paster reference in the "theming" docs, because @erral's one is quite nice ;-)

**Comment by svx** [comment] 2015-08-10 14:19
OK maybe that is a bit harsh, but we will **not** do that by all means :), it was so much work removing paster out of the docs and we are almost there, only diazo and dexterity are left to do.

There will be **NO** paster reference in the docs of Plone 5 :)

**Comment by tisto** [comment] 2015-08-10 14:22
I guess it wouldn't be too hard to refactor the ZopeSkel template to mr.bob. The main question would be how do we handle that inside bobtemplates.plone? Theming differs a lot between Plone 4 and 5. I'm not sure if we really want to put all that into one project/template. Maybe we should factor out the theming part into a separate template.

**Comment by polyester** [comment] 2015-08-10 14:40
Now we have Basic, Dexterity and Theme. So then we would have Basic, Dexterity, Theme, P5_Theme. Seems to make sense, although I can see why separating out is also an option. Still, this is what a lot of people will want: give me something based on Barceloneta so I have a best-practice start.

**Comment by tisto** [comment] 2015-08-10 14:45
This is more an internal problem. If we have four different things within the same template structure, we end up with lots of combined if/else structures that are a nightmare to maintain and test. I worked hard on removing those structures and make bobtemplates.plone testable. I fully agree that we want a Plone 5 Theme option, we just have to make sure we do it in a testable and maintainable way. We need to have a look at the P5 skeleton to decide what's the best way to go.

**Comment by erral** [comment] 2015-08-12 09:35
I have no problem on merging it to bobtemplates.plone; I created it as a
ZopeSkel template because we are currently using it, and it was easier for
me to create a ZopeSkel template than rewriting our templates to mr.bob.

Anyway, I can work on it, but I am currently on holidays, so i can do it
when I am back.

On Mon, Aug 10, 2015 at 4:46 PM, Timo Stollenwerk <notifications@github.com>
wrote:

> This is more an internal problem. If we have four different things within
> the same template structure, we end up with lots of combined if/else
> structures that are a nightmare to maintain and test. I worked hard on
> removing those structures and make bobtemplates.plone testable. I fully
> agree that we want a Plone 5 Theme option, we just have to make sure we do
> it in a testable and maintainable way. We need to have a look at the P5
> skeleton to decide what's the best way to go.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/documentation/issues/193#issuecomment-129478800>
> .
>



-- 
Mikel Larreategi
mlarreategi@codesyntax.com

CodeSyntax
Azitaingo Industrialdea 3 K
E-20600 Eibar
Tel: (+34) 943 82 17 80

**Comment by gforcada** [comment] 2016-07-03 14:15
That's largely done, I only see very few references to zopeskel, so maybe it would be best to open tickets for each of them specifically.

Closing!

**Closed by gforcada** 2016-07-03 14:15 UTC
Labels: 05 type: question, 99 tag: Plone 5, 99 tag: sprint
