### ISSUE TITLE
linkcheckbroken is broken

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1212] opened 2022-03-28 09:54 UTC
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

`make linkcheckbroken` returns an unhelpful error message:

`make: *** [linkcheckbroken] Error 1`

However:

`make linkcheck | GREP_COLORS='0;31' grep -wi "broken\|redirect" --color=auto`

Works just fine. This is identical to the former in `Makefile`.

The only thing that might be causing the error is possibly the check for `html_meta` values returning a non-zero exit code.

This issue affects `plone/volto` and `plone/plone.restapi` as well, except for prefixing the commands with `docs-`.

For now we have changed the CI to use `make linkcheck` instead of `make linkcheckbroken` across all the repos.

**Comment by wolbernd** [comment] 2022-05-04 14:49
@stevepiercy Right now I can't reproduce the problem with my laptop. `make linkcheckbroken` works fine and reports redirects and broken links. 

There are no error messages about empty meta-tags any more. Was this maybe fixed in another issue?

**Comment by stevepiercy** [comment] 2022-05-07 11:48
@wolbernd sorry, I should have put this into proper context.

## documentation

```
$  make linkcheckbroken
cd ./docs/ && /Users/stevepiercy/projects/Plone/documentation/bin/sphinx-build -b linkcheck -d ../_build//doctrees   . ../_build//linkcheck | GREP_COLORS='0;31' grep -wi "broken\|redirect" --color=auto
make: *** [linkcheckbroken] Error 1
```

## documentation/submodules/plone.restapi

```
$ cd submodules/plone.restapi
$  make docs-linkcheckbroken
cd ./docs/source/ && /Users/stevepiercy/projects/Plone/documentation/submodules/plone.restapi/bin/sphinx-build -b linkcheck -d ../_build//doctrees  . ../_build//linkcheck | GREP_COLORS='0;31' egrep -wi broken --color=auto
make: *** [docs-linkcheckbroken] Error 1
```

## documentation/submodules/volto

```
$ cd submodules/volto
$  make docs-linkcheckbroken
make: *** [docs-linkcheckbroken] Error 1
```

It's also a problem in CI/CD.

Linkcheck does not check for meta tag warnings.

**Comment by wolbernd** [comment] 2022-05-09 08:26
@stevepiercy I still can't reproduce the problem on my computer. When I run the above commands I get the output and no error message. 

It might be the fact that `grep` has an exit status of 1 when it hasn't found anything and the calling make-process might interpret any return value !=0 as an error. 

From the grep man page:
```
EXIT STATUS  
       Normally the exit status is 0 if a line is selected, 1 if no
       lines were selected, and 2 if an error occurred.  However, if the
       -q or --quiet or --silent is used and a line is selected, the
       exit status is 0 even if an error occurred.
```
This however does not explain why the error exists on your machine but not on mine. Maybe different make versions handle exit codes differently? Nevertheless could you update your Makefile to the following just to check if that is the cause of the problem?
Just replace line 192 with the following:
`cd $(DOCS_DIR) && $(SPHINXBUILD) -b linkcheck $(ALLSPHINXOPTS) $(BUILDDIR)/linkcheck | GREP_COLORS='0;31' grep -wi "broken\|redirect" --color=auto || test $$? = 1` (watch out for the tab indentation)

This change would allow an exit status of 0 (grep found something) and 1 (grep found nothing, but there was no error). Any other exit code will still lead to an error.

**Comment by stevepiercy** [comment] 2022-05-09 09:42
@wolbernd thank you! Even if I had found that bit in `man grep`, I would never have figured out the shell command syntax to test its return value.

FYI, on my system (macOS 10.15):

```
$ make --version
GNU Make 3.81
```

Running was successful.

```
$ make linkcheckbroken                                                     
cd ./docs/ && /Users/stevepiercy/projects/Plone/documentation/bin/sphinx-build -b linkcheck -d ../_build//doctrees   . ../_build//linkcheck | GREP_COLORS='0;31' grep -wi "broken\|redirect" --color=auto || test $? = 1

Link check complete; look for any errors in the above output  or in ../_build//linkcheck/ .
```

Then I created a broken link and a redirect link, and ran it again.

```
$ make linkcheckbroken
cd ./docs/ && /Users/stevepiercy/projects/Plone/documentation/bin/sphinx-build -b linkcheck -d ../_build//doctrees   . ../_build//linkcheck | GREP_COLORS='0;31' grep -wi "broken\|redirect" --color=auto || test $? = 1
(        glossary: line   11) broken    https://6.dev-docs.plone.org/moose-hair - 404 Client Error: Not Found for url: https://6.dev-docs.plone.org/moose-hair
(        glossary: line   13) redirect  https://docs.voltocms.com/ - permanently to https://6.dev-docs.plone.org/volto/

Link check complete; look for any errors in the above output  or in ../_build//linkcheck/ .

```

Would you please submit PRs in the repositories `plone/volto` and `plone/rest.api` as well as this one, updating both `Makefile` and the relevant `.github/workflows/*` to run `make linkcheckbroken` or `make docs-linkcheckbroken`? And then request me to review?

@ksuess would this be useful in `plone/plone.api`?

**Closed as completed** 2022-05-09 10:04 UTC
Labels: 01 type: bug
