### ISSUE TITLE
broken link at http://docs.plone.org/external/plone.app.dexterity/docs/advanced/index.html

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#585] opened 2016-04-04 16:36 UTC
Sorry, I don't know where to best file this issue. At http://docs.plone.org/external/plone.app.dexterity/docs/advanced/index.html the link to the first page (Defaults) is broken, but looking at https://github.com/plone/plone.app.dexterity/tree/master/docs/advanced it seems everything is normal. Is this perhaps a problem with docs deployment?

**Comment by svx** [comment] 2016-04-04 16:49
You mean if you click on default ? 

This works for me ? Maybe try to clear your cache ?

**Comment by svx** [comment] 2016-04-04 16:52
@tkimnguyen https://youtu.be/V_4XI9IhI4M

**Comment by svx** [comment] 2016-04-05 12:11
@tkimnguyen do you have any update ? I just tested again with the release we pushed to docs.plone.org today and it is working for me

**Comment by svx** [comment] 2016-04-06 17:22
@tkimnguyen I still can't reproduce that, it works for me on on docs.plone.org and wilth local builds.

I will close this for now, feel of course free to re-open :)

**Closed as completed by svx** 2016-04-06 17:22 UTC

**Comment by tkimnguyen** [comment] 2016-04-12 23:33
Hmm... I suspect you went and fixed it behind my back :) I confirm TODAY that it works!
