### ISSUE TITLE
Issue on page /classic-ui/views.html ----> No ToDo Box or Info 

### ISSUE THREAD

**Issue by toalba** [plone/documentation#1420] opened 2023-01-09 12:48 UTC
On the Page [Views](https://6.docs.plone.org/classic-ui/views.html) is the ToDo Box missing

**Comment by stevepiercy** [comment] 2023-01-09 13:55
Closing as duplicate of https://github.com/plone/documentation/issues/1285. It's missing all content because no one has championed the migration of Plone 5.2 Views docs to Plone 6.

**Closed as completed by stevepiercy** 2023-01-09 13:55 UTC
